### ISSUE TITLE
Fix bug: Clashing lesson time prevents user from editing lesson time for the same student

### ISSUE THREAD

**Issue by potaotototo** [AY2425S1-CS2103T-F09-4/tp#149]
<img width="1440" alt="Screenshot 2024-10-29 at 11 45 52 AM" src="https://github.com/user-attachments/assets/f26c98a1-ae2a-44fc-a1ba-30ace434cf3d">

# Problem
If editing the lesson time **for the same student** from one to another with the new lesson time overlapping with the previous, the edit is not permitted.

**Comment by luileng** [comment]
Fixed with #197
