### ISSUE TITLE
Fix Bug: No error messages given when lesson ends at 0000

### ISSUE THREAD

**Issue by curtischang2510** [AY2425S1-CS2103T-F09-4/tp#182]
- Based on our implementation we do not allow lesson to overflow to the next day, hence a lesson ending at midnight is not allowed , for example `monday 2300-0000` because it technically ends on Tuesday 
- This is not written in the error messages or in the user guides which could mislead people to think that is a bug. 
- Change the commands and add an error message indicating that lesson timings should be within the range `0000-2359`

**Comment by luileng** [comment]
Resolved in #189
