### ISSUE TITLE
[PE-D][Tester D] Tags that are too long are cut off on the left panel

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-4/tp#267]
Steps to reproduce:
type in "add n/name p/999 t/123456789123456789123456789123456789".

Actual output on the left screen: 

![image.png](https://raw.githubusercontent.com/rachelyeohm/ped/main/files/0ed6ffb7-5bb4-49d3-b755-36c8cf14d331.png)
Essentially, long tags do not wrap around or show any indication of being cut off intentionally like "...". It just gets cut off on the left panel.

I understand that this has been listed under current limitations. However as mentioned, this does not prevent testers from being able to report them as bugs, unfortunately. All the best!

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: rachelyeohm/ped#9

**Comment by luileng** [comment]
This is a minor UI bug that we will not resolve in the next iteration (v1.6)

Furthermore, it is unlikely that users will use such long tags
