### ISSUE TITLE
[PE-D][Tester D] Find feature is unable to find with certain parameters e.g. phone, email, tele user

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-4/tp#270]
![image.png](https://raw.githubusercontent.com/rachelyeohm/ped/main/files/9adb8de4-acf7-4d55-81ad-3b71fb06d401.png)

The find feature is unable to be used to find with certain parameters, like phone, email and telegram username. I believe this is less useful to the intended target user, because they might need to search by any one of these features (e.g. if they remember the telegram username better because the student's name is complicated).

It would be good to allow functionalities for the other parameters.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: rachelyeohm/ped#10

**Comment by luileng** [comment]
As discussed, users are unlikely to search by phone number etc, which was why we decided not to include these parameters. Perhaps this could be made clearer in the user guide (that the parameters chosen are useful for the user)
