### ISSUE TITLE
[PE-D][Tester D] Explanation of undo and data archiving features not completed in DG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-4/tp#283]
![image.png](https://raw.githubusercontent.com/rachelyeohm/ped/main/files/ca760b51-f06f-482d-a33c-70d69b49596a.png)

The undo and data archiving feature's description are stated as not completed in the DG. This could be jarring to a developer reading through it. A suggestion would be to delete the entire data archiving section if the team does not plan to explain it.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: rachelyeohm/ped#18

**Comment by luileng** [comment]
As discussed, we will likely be removing this from the DG in the next iteration (v1.6)
