### ISSUE TITLE
[PE-D][Tester B] Redo command is not yet implemented

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-4/tp#289]
![redo.png](https://raw.githubusercontent.com/hpcman/ped/main/files/a36b750c-89f0-4b11-b6d2-3292a5992869.png)
There is an explanation of how redo command works in DG but it is not yet implemented in the application.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: hpcman/ped#7

**Comment by luileng** [comment]
This is under proposed features and as such is not meant to be implemented for v1.5
