### ISSUE TITLE
[PE-D][Tester A] Edit Command Unable to Pick Up Existing Field Values

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-4/tp#310]
When a user wants to change the phone number or any other fields of a student to the same value, the edit command runs without showing errors or warning.

E.g. a person with phone number 98765432,
`edit p/98765432` runs without any error. However, it should show a warning to tell the user that they are entering a duplicate / already existed value.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: chengzihao123/ped#10

**Comment by luileng** [comment]
This feature is acceptable as it does not create problems with the rest of the data like creating duplicate names etc
